### ISSUE TITLE
Non-sequential Section Numbering

### ISSUE THREAD

**Issue by a2** [adicu/data.adicu.com#28]
Courses v2 doesn’t handle non-sequential section numbering. For example, PHYS C1493, next semester’s physics lab, has sections numbered 1, 2, 4, 6, 7, 9, 10, and 12, but the API returns an array of 8 sections.

**Comment by a2** [comment]
I would offer to fork and fix, but if I changed it to return a dictionary instead of an array, it could break [courses.adicu.com](http://courses.adicu.com).

**Comment by rbtying** [comment]
Fix both!

**Comment by a2** [comment]
@rbtying I don't see where to make the change in [app/js/services.coffee](https://github.com/adicu/Courses/blob/master/app/js/services.coffee).

**Comment by rbtying** [comment]
You should edit getSections() to work properly with a dictionary instead 
of a list, I think, as well as addSectionFromCallNumber()

**Comment by a2** [comment]
This is a little over my head. [data.adicu.com](http://data.adicu.com) sorts sections by call number and courses by course ID. This is a bit more involved than I thought it would be.

Thoughts, @znewman01 or @jphines?

**Comment by znewman01** [comment]
It isn't meant to be an array (I.e. with indexes) so much as a list. And all the section info is there, so I don't think this is super critical.

That said, it's a fine change to make. I can help work on it once other, more pressing Courses fixes are made

**Comment by a2** [comment]
Which field contains the section number? That's the part I couldn't find.

**Comment by znewman01** [comment]
Ahh, that's totally my bad. There's a "SectionFull" field that lists the full name of the section (i.e. "COMS1007W001") that contains the section in the last three digits. it's been in the repo for a couple of days but i forgot to deploy to Heroku.

we should have a section number field too, but that's another (pretty easily solved) issue. i'll open one for that

**Comment by rbtying** [comment]
Zack,

Is there any way to add the field "COMSW1007" in the /courses and 
/sections endpoints? Primarily because people who do search by section 
number tend to remember the letter in there, as well.

Sometime today I'll write a parser for sectionfull that returns the 
bulletin URL, though.

Regards,
-- Robert Ying

**Comment by znewman01** [comment]
we could begin using "COMSW1007" instead of "COMS1007" as a primary key for courses and then use that as the foreign key for sections. does that make more sense?

the only thing for me is that i personally don't remember the letter and i do tend to search by course number. so i think we should keep both (i guess the way to do that is to have elasticsearch index both and have an OR query between them)

**Comment by rbtying** [comment]
The primary key as it stands is fine, I think... breaking what we have 
is bad, too. I do think it's important to index both in elasticsearch 
and query by both, though.

**Comment by znewman01** [comment]
turns out it already was being indexed, this was easy fix to make!

**Comment by zhemao** [comment]
It seems like this will be resolved once #29 is. Shall I close this one?

**Comment by znewman01** [comment]
sgtm
